server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:hezihaog/microservicecloud-config.git #Github上面的git仓库地址
          uri: https://github.com/hezihaog/microservicecloud-config.git #Github上面的git仓库地址