server:
  port: 7003

eureka:
  server:
    enable-self-preservation: true #是否开启自我保护机制，默认为true，就是开启
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，不需要检索服务
    service-url:
      #单机
      #default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置Eureka Server交互的地址查询服务和注册服务都需要这个依赖
      #集群
      default-zone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka